# wiki build and deploy 

name: wiki-build-workflow

on:
  push:
    branches: [ "main" ]
    paths:
      - 'docs/**'
      - 'i18n/**'
      - 'blog/**'
      - 'src/**'
      - 'static/**'
      - '.github/workflows/**'
      - 'docusaurus.config.ts'
      - 'package.json'
      - 'sidebars.ts'

jobs:
  build:
    name: Build wiki
    if: github.repository == 'bigtreetech-beta/bigtreetech-wiki-neo'
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v6
    
    - name: Setup Environment
      uses: actions/setup-node@v6
      with:
        node-version: '24.x'
        
    - name: Install dependencies
      run: yarn install
      
    - name: build wiki 
      run: yarn run build

    # config rclone
    - name: Install rclone
      run: |
        sudo apt update
        sudo apt install -y rclone
    
    # Aliyun OSS
    - name: Configure rclone (Aliyun OSS)
      run: |
        rclone config create aliyun s3 \
          provider=Alibaba \
          access_key_id=${{ secrets.OSS_KEY_ID }} \
          secret_access_key=${{ secrets.OSS_KEY_SECRET }} \
          endpoint=https://oss-cn-shenzhen.aliyuncs.com \
          region=cn-shenzhen \

    - name: Copy build to Aliyun OSS
      run: |
        rclone sync build aliyun:btt-wiki \
          --exclude "/robots.txt" \
          --exclude "/favicon.ico" \
          --exclude "/404.html" \
          --fast-list \
          --checkers=32 \
          --transfers=16 \
          --progress
    
    # Cloudflare R2
    - name: Configure rclone (Cloudflare R2 only)
      run: |
        rclone config create r2 s3 \
          provider=Cloudflare \
          access_key_id=${{ secrets.R2_ACCESS_KEY_ID }} \
          secret_access_key=${{ secrets.R2_SECRET_ACCESS_KEY }} \
          endpoint=https://${{ secrets.R2_ACCOUNT_ID }}.r2.cloudflarestorage.com

    - name: Copy build to Cloudflare R2
      run: |
        rclone sync build r2:${{ secrets.R2_BUCKET }} \
          --exclude "/robots.txt" \
          --exclude "/favicon.ico" \
          --fast-list \
          --checkers=32 \
          --transfers=16 \
          --stats 30s \
          --stats-one-line \
          --s3-no-head
