# this workflow use as pull request check 

name: wiki-PR-build-workflow

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - 'docs/**'
      - 'i18n/**'
      - 'blog/**'
      - 'src/**'
      - 'static/**'
      - '.github/workflows/**'
      - 'docusaurus.config.ts'
      - 'package.json'
      - 'sidebars.ts'

jobs:
  lint:
    name: Build wiki
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - name: Run Meow Linter
      uses: Neko-vecter/meow-lint@v1.0.6
      with:
        github_token: ${{ github.token }}
          
    - name: Use Node.js
      uses: actions/setup-node@v6
      with:
        node-version: '24.x'
        
      # init yarn 
    - name: Install dependencies
      run: yarn

      # build 
    - name: build wiki 
      run: yarn run build
